#!/bin/sh

if ! getent passwd mongod >/dev/null 2>&1; then
    adduser --system --no-create-home --group mongod
fi

if [ ! -f /var/log/plm.log ]; then
    install -m 0755 -o mongod -g mongod /dev/null /var/log/plm.log
fi

#DEBHELPER#

exit 0
